build:
  image: docker:19.03.11
  stage: build
  services:
    - docker:19.03.11-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
    VUE_APP_BACKEND_URL: $BACKEND_URL
    VUE_APP_AUTH: STATIC
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg VUE_APP_BACKEND_URL=$BACKEND_URL --build-arg VUE_APP_AUTH=STATIC -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
